name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run a one-line script
        run: echo hello world

      - name: Run multi-line script
        run: |
          echo first line
          echo second line
